apiVersion: apps/v1
kind: Deployment
metadata:
  name: immudb
  namespace: tracing-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immudb
  template:
    metadata:
      labels:
        app: immudb
    spec:
      priorityClassName: core-services
      nodeSelector:
        chaimeleon.eu/target: core-services
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60

      securityContext:
        runAsNonRoot: true
        runAsUser: 3322
        runAsGroup: 3322
        fsGroup: 3322
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: immudb
          image: codenotary/immudb:1.11.2-bullseye-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: immudb-psql
              containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: immudb-config
            - secretRef: 
                name: immudb-secrets

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 4Gi
            limits:
              cpu: "1"
              memory: 4Gi
          volumeMounts:
          - mountPath: /var/lib/immudb
            name: immudb-storage
            subPath: immudb

      volumes:
        - name: immudb-storage
          persistentVolumeClaim:
            claimName: immudb-data