apiVersion: apps/v1
kind: Deployment
metadata:
  name: immudb
  namespace: tracing-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immudb
  template:
    metadata:
      labels:
        app: immudb
    spec:
      priorityClassName: core-services
      nodeSelector:
        chaimeleon.eu/target: core-services
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60

      securityContext:   
        fsGroup: 2000
      containers:
        - name: immudb
          image: codenotary/immudb:1.11.1-bullseye-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: immudb-psql
              containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: immudb-config
            - secretRef: 
                name: immudb-secrets

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 4Gi
            limits:
              cpu: "1"
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immudb-data
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi