
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immudb-data
  namespace: tracing-service
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi