database:
  # The name of the user utilized by the application to connect to ImmuDB; The password has to be set either via an ENV var or a file
  user: myuser
  # The host of the ImmuDB instance
  host: localhost
  # The port used to connect to the ImmuDB instance via the Postgres wire protocol
  port: 5432
  # The name of the database
  name: tracing
  # Pool settings
  pool:
    # Min num of threads in the pool
    min_size: 3
    # Max num of threads in the pool
    max_size: 3
oidc:
  # Base URL of the keycloak instance
  url: <URL_of_OIDC_provider>
  # Keycloak realm that contains the client
  realm: realm
  # The name of the keycloak client
  client: tracing
  # List of audiences that are accepted by this app
  audiences: [
    "tracing"
  ]
api:
  # The prefix after the host/port that is added to the root of the path
  prefix:
  v2:
    # Max num of traces that are returned by the get traces GET call
    default_traces_limit: 20