apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-service-config
  namespace: tracing-service
data:
  settings.yml: |
    database:
      user: tracing
      host: 
      port: 5432
      name: tracing
      pool:
        min_size: 3
        max_size: 3
    oidc:
      url: 
      realm: 
      client: 
      audiences: [
      ]
    api:
      v2:
        default_traces_limit: 20